server:
  servlet:
   context-path: /api
  port: 8081
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_adminappopenapi?createDatabaseIfNotExist=true
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: spring-admin

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

info:
  application:
    name: admin-app
    version: '@project.version@'




