openapi: "3.0.0"

info:
  title: API Roles
  version: "1.0"
  description: Ecommerce API

servers:
  - url: http://localhost:8080/admin_app/api

tags:
  - name: Roles
    description: Roles specific data.

paths:
  /roles:
    get:
      tags:
        - Roles
      summary: Get All Actifs Roles
      operationId: getAllRoles
      parameters:
        - name: currentPage
          in: query
          required: true
          schema:
            type: integer
            format: int32
        - name: sizePage
          in: query
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: SUCCESS
          content:
            'application/json':
              schema:
                $ref: '../model/roles/RolesResultListDTO.yml'
        '404':
          description: NOT FOUND
        '400':
          description: BAD REQUEST
    post:
      tags:
        - Roles
      summary: Add a roles
      operationId: createRole
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../model/roles/RoleDTO.yml'
            example:
              idProduct: 0
              name: oranges
              qtStock: 1293
      responses:
        '200':
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '../model/roles/RoleDTO.yml'
              example:
                idProduct: 0
                name: oranges
                qtStock: 1293
        '404':
          description: NOT FOUND
        '400':
          description: BAD REQUEST
    put:
      tags:
        - Roles
      summary: Add a role
      operationId: updateRole
      parameters:
        - name: idRole
          in: path
          required: true
          schema:
            type: integer
            format: int64
          example:
            idProduct: 1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../model/roles/RoleDTO.yml'
            examples:
              product:
                value:
                  idProduct: 1
                  name: pc gamer
                  qtStock: 289
      responses:
        '200':
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '../model/roles/RoleDTO.yml'
              example:
                idProduct: 1
                name: pc gamer
                qtStock: 289
        '404':
          description: NOT FOUND
        '400':
          description: BAD REQUEST
  /roles-reference:
    get:
      tags:
        - Roles
      summary: Retrieve an role
      operationId: getRole
      parameters:
        - name: idRole
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: SUCCESS
          content:
            'application/json':
              schema:
                $ref: '../model/roles/RoleDTO.yml'
        '404':
          description: NOT FOUND
        '400':
          description: BAD REQUEST